// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd2Ze3KQNV9l2lps57n1ok4gIxeAXJ724',
    appId: '1:275765391641:web:d1b1113ed68fe049a71588',
    messagingSenderId: '275765391641',
    projectId: 'uaigo-53190',
    authDomain: 'uaigo-53190.firebaseapp.com',
    databaseURL: 'https://uaigo-53190-default-rtdb.firebaseio.com',
    storageBucket: 'uaigo-53190.appspot.com',
    measurementId: 'G-FEPW5BGLVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqBFPIYO2nz3JOqPfLsLCrUmhRIygXLIU',
    appId: '1:275765391641:android:58256b8b88466381a71588',
    messagingSenderId: '275765391641',
    projectId: 'uaigo-53190',
    databaseURL: 'https://uaigo-53190-default-rtdb.firebaseio.com',
    storageBucket: 'uaigo-53190.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACSreeUnEa9e1absEmdDLUqROAFt-OzSI',
    appId: '1:275765391641:ios:9b0566e140a104dba71588',
    messagingSenderId: '275765391641',
    projectId: 'uaigo-53190',
    databaseURL: 'https://uaigo-53190-default-rtdb.firebaseio.com',
    storageBucket: 'uaigo-53190.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACSreeUnEa9e1absEmdDLUqROAFt-OzSI',
    appId: '1:275765391641:ios:9b0566e140a104dba71588',
    messagingSenderId: '275765391641',
    projectId: 'uaigo-53190',
    databaseURL: 'https://uaigo-53190-default-rtdb.firebaseio.com',
    storageBucket: 'uaigo-53190.appspot.com',
    iosBundleId: 'com.example.example',
  );
}
